default: &default
      adapter: postgresql
      encoding: SQL_ASCII
      pool: 5
      username: ubuntu
      password: 123

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production